//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.food
{ 
    public enum cookDifficulty
    {
        /// <summary>
        /// 简单
        /// </summary>
        easy = 1,
        /// <summary>
        /// 普通
        /// </summary>
        normal = 2,
        /// <summary>
        /// 困难
        /// </summary>
        hard = 3,
    }

} 
