//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.food
{ 
    public enum cookTools
    {
        /// <summary>
        /// 炒锅
        /// </summary>
        Cook = 1,
        /// <summary>
        /// 煮锅
        /// </summary>
        Boil = 2,
        /// <summary>
        /// 炸锅
        /// </summary>
        Fry = 3,
        /// <summary>
        /// 蒸笼
        /// </summary>
        Steam = 4,
        /// <summary>
        /// 烤架
        /// </summary>
        Barbecue = 5,
    }

} 
