//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.food
{ 
    public enum flavorTag
    {
        /// <summary>
        /// 肉
        /// </summary>
        Rou = 1001,
        /// <summary>
        /// 水产
        /// </summary>
        ShuiChan = 1002,
        /// <summary>
        /// 素
        /// </summary>
        Su = 1003,
        /// <summary>
        /// 实惠
        /// </summary>
        ShiHui = 1004,
        /// <summary>
        /// 昂贵
        /// </summary>
        AngGui = 1005,
        /// <summary>
        /// 家常
        /// </summary>
        JiaChang = 1006,
        /// <summary>
        /// 凉菜
        /// </summary>
        LiangCai = 1007,
        /// <summary>
        /// 卤制品
        /// </summary>
        LuZhiPing = 1008,
        /// <summary>
        /// 荤素搭配
        /// </summary>
        HunSu = 1009,
        /// <summary>
        /// 野味
        /// </summary>
        YeWei = 1010,
        /// <summary>
        /// 小炒
        /// </summary>
        XiaoChao = 1011,
        /// <summary>
        /// 烧烤
        /// </summary>
        ShaoKao = 1012,
        /// <summary>
        /// 重油
        /// </summary>
        ZhongYou = 1013,
        /// <summary>
        /// 汤羹
        /// </summary>
        TangGeng = 1014,
        /// <summary>
        /// 热气
        /// </summary>
        ReQi = 1015,
        /// <summary>
        /// 清淡
        /// </summary>
        QingDan = 1016,
        /// <summary>
        /// 酸
        /// </summary>
        Suan = 1017,
        /// <summary>
        /// 甜
        /// </summary>
        Tian = 1018,
        /// <summary>
        /// 苦
        /// </summary>
        Ku = 1019,
        /// <summary>
        /// 辣
        /// </summary>
        La = 1020,
        /// <summary>
        /// 咸
        /// </summary>
        XianWei = 1021,
        /// <summary>
        /// 鲜
        /// </summary>
        Xian = 1022,
        /// <summary>
        /// 臭
        /// </summary>
        Chou = 1023,
        /// <summary>
        /// 饱腹
        /// </summary>
        BaoFu = 1024,
        /// <summary>
        /// 小巧
        /// </summary>
        XiaoQiao = 1025,
        /// <summary>
        /// 清凉
        /// </summary>
        QingLiang = 1026,
        /// <summary>
        /// 暖胃
        /// </summary>
        NuanWei = 1027,
        /// <summary>
        /// 烫嘴
        /// </summary>
        TangZui = 1028,
        /// <summary>
        /// 冰爽
        /// </summary>
        BingShuang = 1029,
        /// <summary>
        /// 香酥
        /// </summary>
        XiangSu = 1030,
        /// <summary>
        /// 减肥
        /// </summary>
        JianFei = 1031,
        /// <summary>
        /// 嫩
        /// </summary>
        Nen = 1032,
        /// <summary>
        /// 老
        /// </summary>
        Lao = 1033,
        /// <summary>
        /// 软烂
        /// </summary>
        RuanLan = 1034,
        /// <summary>
        /// 开胃
        /// </summary>
        KaiWei = 1035,
    }

} 
