//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.food
{ 
    public enum materialType
    {
        /// <summary>
        /// 肉类
        /// </summary>
        Meat = 1,
        /// <summary>
        /// 海鲜
        /// </summary>
        Seafood = 2,
        /// <summary>
        /// 蔬菜
        /// </summary>
        Vegetable = 3,
        /// <summary>
        /// 其它
        /// </summary>
        Other = 4,
    }

} 
