//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.food
{ 

public sealed partial class qte_info :  Bright.Config.BeanBase 
{
    public qte_info(JSONNode _json) 
    {
        { if(!_json["start_area"].IsNumber) { throw new SerializationException(); }  StartArea = _json["start_area"]; }
        { if(!_json["end_area"].IsNumber) { throw new SerializationException(); }  EndArea = _json["end_area"]; }
        { if(!_json["qte_id"].IsNumber) { throw new SerializationException(); }  QteId = _json["qte_id"]; }
        PostInit();
    }

    public qte_info(float start_area, float end_area, int qte_id ) 
    {
        this.StartArea = start_area;
        this.EndArea = end_area;
        this.QteId = qte_id;
        PostInit();
    }

    public static qte_info Deserializeqte_info(JSONNode _json)
    {
        return new food.qte_info(_json);
    }

    /// <summary>
    /// 生效区间百分比
    /// </summary>
    public float StartArea { get; private set; }
    /// <summary>
    /// 生效区间百分比
    /// </summary>
    public float EndArea { get; private set; }
    /// <summary>
    /// 对应qte操作
    /// </summary>
    public int QteId { get; private set; }

    public const int __ID__ = -2099369029;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StartArea:" + StartArea + ","
        + "EndArea:" + EndArea + ","
        + "QteId:" + QteId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
