//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.food
{ 
    public enum qteTag
    {
        /// <summary>
        /// 加盐
        /// </summary>
        Salt = 1,
        /// <summary>
        /// 加醋
        /// </summary>
        Vinegar = 2,
    }

} 
