//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.food
{ 
    public enum rawType
    {
        /// <summary>
        /// 海鲜
        /// </summary>
        SeaFood = 0,
        /// <summary>
        /// 肉
        /// </summary>
        Meat = 1,
        /// <summary>
        /// 蔬菜
        /// </summary>
        Vegetable = 2,
        /// <summary>
        /// 其他
        /// </summary>
        Others = 3,
    }

} 
