//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.food
{ 

public sealed partial class TbFlavour
{
    private readonly Dictionary<int, food.FlavourInfo> _dataMap;
    private readonly List<food.FlavourInfo> _dataList;
    
    public TbFlavour(JSONNode _json)
    {
        _dataMap = new Dictionary<int, food.FlavourInfo>();
        _dataList = new List<food.FlavourInfo>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = food.FlavourInfo.DeserializeFlavourInfo(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, food.FlavourInfo> DataMap => _dataMap;
    public List<food.FlavourInfo> DataList => _dataList;

    public food.FlavourInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public food.FlavourInfo Get(int key) => _dataMap[key];
    public food.FlavourInfo this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}