//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.food
{ 

public sealed partial class TbFoodInfo
{
    private readonly Dictionary<int, food.FoodBaseInfo> _dataMap;
    private readonly List<food.FoodBaseInfo> _dataList;
    
    public TbFoodInfo(JSONNode _json)
    {
        _dataMap = new Dictionary<int, food.FoodBaseInfo>();
        _dataList = new List<food.FoodBaseInfo>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = food.FoodBaseInfo.DeserializeFoodBaseInfo(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, food.FoodBaseInfo> DataMap => _dataMap;
    public List<food.FoodBaseInfo> DataList => _dataList;

    public food.FoodBaseInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public food.FoodBaseInfo Get(int key) => _dataMap[key];
    public food.FoodBaseInfo this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}