//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.food
{ 

public sealed partial class TbQTEGroup
{
    private readonly Dictionary<int, food.QTEGroupInfo> _dataMap;
    private readonly List<food.QTEGroupInfo> _dataList;
    
    public TbQTEGroup(JSONNode _json)
    {
        _dataMap = new Dictionary<int, food.QTEGroupInfo>();
        _dataList = new List<food.QTEGroupInfo>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = food.QTEGroupInfo.DeserializeQTEGroupInfo(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, food.QTEGroupInfo> DataMap => _dataMap;
    public List<food.QTEGroupInfo> DataList => _dataList;

    public food.QTEGroupInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public food.QTEGroupInfo Get(int key) => _dataMap[key];
    public food.QTEGroupInfo this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}