//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.common
{ 

public sealed partial class appear_time :  Bright.Config.BeanBase 
{
    public appear_time(JSONNode _json) 
    {
        { if(!_json["weekday"].IsNumber) { throw new SerializationException(); }  Weekday = (common.WeekDay)_json["weekday"].AsInt; }
        { if(!_json["enter_time"].IsObject) { throw new SerializationException(); }  EnterTime = common.Time.DeserializeTime(_json["enter_time"]);  }
        { if(!_json["leave_time"].IsObject) { throw new SerializationException(); }  LeaveTime = common.Time.DeserializeTime(_json["leave_time"]);  }
        PostInit();
    }

    public appear_time(common.WeekDay weekday, common.Time enter_time, common.Time leave_time ) 
    {
        this.Weekday = weekday;
        this.EnterTime = enter_time;
        this.LeaveTime = leave_time;
        PostInit();
    }

    public static appear_time Deserializeappear_time(JSONNode _json)
    {
        return new common.appear_time(_json);
    }

    /// <summary>
    /// 平日
    /// </summary>
    public common.WeekDay Weekday { get; private set; }
    /// <summary>
    /// 进入时间
    /// </summary>
    public common.Time EnterTime { get; private set; }
    /// <summary>
    /// 离开时间
    /// </summary>
    public common.Time LeaveTime { get; private set; }

    public const int __ID__ = 281201588;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        EnterTime?.Resolve(_tables);
        LeaveTime?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        EnterTime?.TranslateText(translator);
        LeaveTime?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Weekday:" + Weekday + ","
        + "EnterTime:" + EnterTime + ","
        + "LeaveTime:" + LeaveTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
