//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.common
{ 

public sealed partial class behaviour_group :  Bright.Config.BeanBase 
{
    public behaviour_group(JSONNode _json) 
    {
        { if(!_json["behaviour"].IsNumber) { throw new SerializationException(); }  Behaviour = (character.behaviour)_json["behaviour"].AsInt; }
        { if(!_json["weight"].IsNumber) { throw new SerializationException(); }  Weight = _json["weight"]; }
        PostInit();
    }

    public behaviour_group(character.behaviour behaviour, int weight ) 
    {
        this.Behaviour = behaviour;
        this.Weight = weight;
        PostInit();
    }

    public static behaviour_group Deserializebehaviour_group(JSONNode _json)
    {
        return new common.behaviour_group(_json);
    }

    /// <summary>
    /// 行为
    /// </summary>
    public character.behaviour Behaviour { get; private set; }
    /// <summary>
    /// 权重
    /// </summary>
    public int Weight { get; private set; }

    public const int __ID__ = 966689402;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Behaviour:" + Behaviour + ","
        + "Weight:" + Weight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
