//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.common
{ 
    public enum bubbleType
    {
        /// <summary>
        /// 主线
        /// </summary>
        MainLine = 1,
        /// <summary>
        /// 对话
        /// </summary>
        Talk = 2,
        /// <summary>
        /// 精准下单
        /// </summary>
        SpecifiedOrder = 3,
        /// <summary>
        /// 模糊订单
        /// </summary>
        Omakase = 4,
        /// <summary>
        /// 模棱两可
        /// </summary>
        HybridOrder = 5,
        /// <summary>
        /// 精准评论
        /// </summary>
        SpecifiedComment = 6,
        /// <summary>
        /// 模糊评论
        /// </summary>
        OmakaseComment = 7,
        /// <summary>
        /// 模棱两可评论
        /// </summary>
        HybridComment = 8,
    }

} 
