//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.common
{ 
    public enum bubbleType
    {
        /// <summary>
        /// 对话
        /// </summary>
        Talk = 1,
        /// <summary>
        /// 下单
        /// </summary>
        Order = 2,
        /// <summary>
        /// 评论
        /// </summary>
        Comment = 3,
    }

} 
