//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.common
{ 
    public enum Season
    {
        /// <summary>
        /// 春季
        /// </summary>
        Spring = 1,
        /// <summary>
        /// 夏季
        /// </summary>
        Summer = 2,
        /// <summary>
        /// 秋季
        /// </summary>
        Autumn = 3,
        /// <summary>
        /// 冬季
        /// </summary>
        Winnter = 4,
    }

} 
