//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.common
{ 
    public enum Weather
    {
        /// <summary>
        /// 晴天
        /// </summary>
        Sunshine = 1,
        /// <summary>
        /// 雨天
        /// </summary>
        Rain = 2,
        /// <summary>
        /// 下雪
        /// </summary>
        Snow = 3,
        /// <summary>
        /// 台风
        /// </summary>
        Typhoon = 4,
        /// <summary>
        /// 暴风雪
        /// </summary>
        SnowStorm = 5,
    }

} 
