//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.common
{ 
    public enum WeekDay
    {
        /// <summary>
        /// 周一
        /// </summary>
        Monday = 1,
        /// <summary>
        /// 周二
        /// </summary>
        Tuesday = 2,
        /// <summary>
        /// 周三
        /// </summary>
        Wednesday = 3,
        /// <summary>
        /// 周四
        /// </summary>
        Thursday = 4,
        /// <summary>
        /// 周五
        /// </summary>
        Friday = 5,
        /// <summary>
        /// 周六
        /// </summary>
        Saturday = 6,
        /// <summary>
        /// 周日
        /// </summary>
        Sunday = 7,
        /// <summary>
        /// 全部
        /// </summary>
        AllWeekDay = 8,
        /// <summary>
        /// 周八
        /// </summary>
        IllegelDay = 9,
    }

} 
