//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.system
{ 

public sealed partial class DayScheduler :  Bright.Config.BeanBase 
{
    public DayScheduler(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["Seaon"].IsNumber) { throw new SerializationException(); }  Seaon = (common.Season)_json["Seaon"].AsInt; }
        { if(!_json["Day"].IsNumber) { throw new SerializationException(); }  Day = _json["Day"]; }
        { if(!_json["WeatherGroupId"].IsNumber) { throw new SerializationException(); }  WeatherGroupId = _json["WeatherGroupId"]; }
        PostInit();
    }

    public DayScheduler(int id, common.Season Seaon, int Day, int WeatherGroupId ) 
    {
        this.Id = id;
        this.Seaon = Seaon;
        this.Day = Day;
        this.WeatherGroupId = WeatherGroupId;
        PostInit();
    }

    public static DayScheduler DeserializeDayScheduler(JSONNode _json)
    {
        return new system.DayScheduler(_json);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 季节
    /// </summary>
    public common.Season Seaon { get; private set; }
    /// <summary>
    /// 日期
    /// </summary>
    public int Day { get; private set; }
    /// <summary>
    /// 天气组
    /// </summary>
    public int WeatherGroupId { get; private set; }

    public const int __ID__ = -1814299138;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Seaon:" + Seaon + ","
        + "Day:" + Day + ","
        + "WeatherGroupId:" + WeatherGroupId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
