//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.system
{ 

public sealed partial class TbDayScheduler
{
    private readonly Dictionary<int, system.DayScheduler> _dataMap;
    private readonly List<system.DayScheduler> _dataList;
    
    public TbDayScheduler(JSONNode _json)
    {
        _dataMap = new Dictionary<int, system.DayScheduler>();
        _dataList = new List<system.DayScheduler>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = system.DayScheduler.DeserializeDayScheduler(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, system.DayScheduler> DataMap => _dataMap;
    public List<system.DayScheduler> DataList => _dataList;

    public system.DayScheduler GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public system.DayScheduler Get(int key) => _dataMap[key];
    public system.DayScheduler this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}