//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.character
{ 

public sealed partial class BehaviourGroup :  Bright.Config.BeanBase 
{
    public BehaviourGroup(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { var __json0 = _json["group"]; if(!__json0.IsArray) { throw new SerializationException(); } Group = new System.Collections.Generic.List<common.behaviour_group>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { common.behaviour_group __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = common.behaviour_group.Deserializebehaviour_group(__e0);  }  Group.Add(__v0); }   }
        PostInit();
    }

    public BehaviourGroup(int id, System.Collections.Generic.List<common.behaviour_group> group ) 
    {
        this.Id = id;
        this.Group = group;
        PostInit();
    }

    public static BehaviourGroup DeserializeBehaviourGroup(JSONNode _json)
    {
        return new character.BehaviourGroup(_json);
    }

    public int Id { get; private set; }
    public System.Collections.Generic.List<common.behaviour_group> Group { get; private set; }

    public const int __ID__ = 1080077639;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Group) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Group) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Group:" + Bright.Common.StringUtil.CollectionToString(Group) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
