//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.character
{ 
    public enum behaviour
    {
        /// <summary>
        /// 进入
        /// </summary>
        Enter = 1,
        /// <summary>
        /// 点餐
        /// </summary>
        Order = 2,
        /// <summary>
        /// 点菜
        /// </summary>
        OrderMeal = 3,
        /// <summary>
        /// 点饮料
        /// </summary>
        OrderDrink = 4,
        /// <summary>
        /// 闲聊
        /// </summary>
        Talk = 5,
        /// <summary>
        /// 离开
        /// </summary>
        Leave = 6,
        /// <summary>
        /// 等待回复
        /// </summary>
        WaitReply = 7,
        /// <summary>
        /// 等待上菜
        /// </summary>
        WaitOrder = 8,
        /// <summary>
        /// 吃法
        /// </summary>
        Eating = 9,
        /// <summary>
        /// 思考
        /// </summary>
        Thinking = 10,
        /// <summary>
        /// 评论
        /// </summary>
        Comment = 11,
    }

} 
