//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.character
{ 
    public enum behaviour
    {
        /// <summary>
        /// 离开
        /// </summary>
        Leave = 1,
        /// <summary>
        /// 点餐
        /// </summary>
        OrderMeal = 2,
        /// <summary>
        /// 点饮料
        /// </summary>
        OrderDrink = 3,
        /// <summary>
        /// 闲聊
        /// </summary>
        Talk = 4,
        /// <summary>
        /// 进入
        /// </summary>
        Enter = 5,
        /// <summary>
        /// 等待
        /// </summary>
        Waiting = 6,
        /// <summary>
        /// 吃法
        /// </summary>
        Eating = 7,
    }

} 
