//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.character
{ 

public sealed partial class CharacterBaseInfo :  Bright.Config.BeanBase 
{
    public CharacterBaseInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["res_path"].IsString) { throw new SerializationException(); }  ResPath = _json["res_path"]; }
        PostInit();
    }

    public CharacterBaseInfo(int id, string name, string desc, string res_path ) 
    {
        this.Id = id;
        this.Name = name;
        this.Desc = desc;
        this.ResPath = res_path;
        PostInit();
    }

    public static CharacterBaseInfo DeserializeCharacterBaseInfo(JSONNode _json)
    {
        return new character.CharacterBaseInfo(_json);
    }

    /// <summary>
    /// npcid
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 资源路径
    /// </summary>
    public string ResPath { get; private set; }

    public const int __ID__ = -1834518077;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "ResPath:" + ResPath + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
