//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.character
{ 

public sealed partial class CharacterPhase :  Bright.Config.BeanBase 
{
    public CharacterPhase(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { var __json0 = _json["regions"]; if(!__json0.IsArray) { throw new SerializationException(); } Regions = new System.Collections.Generic.List<common.value_region_param>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { common.value_region_param __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = common.value_region_param.Deserializevalue_region_param(__e0);  }  Regions.Add(__v0); }   }
        PostInit();
    }

    public CharacterPhase(int id, string name, System.Collections.Generic.List<common.value_region_param> regions ) 
    {
        this.Id = id;
        this.Name = name;
        this.Regions = regions;
        PostInit();
    }

    public static CharacterPhase DeserializeCharacterPhase(JSONNode _json)
    {
        return new character.CharacterPhase(_json);
    }

    /// <summary>
    /// npcId
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    public System.Collections.Generic.List<common.value_region_param> Regions { get; private set; }

    public const int __ID__ = -789102249;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Regions) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Regions) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Regions:" + Bright.Common.StringUtil.CollectionToString(Regions) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
