//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.character
{ 

public sealed partial class Crowd :  Bright.Config.BeanBase 
{
    public Crowd(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["weekDay"].IsNumber) { throw new SerializationException(); }  WeekDay = (common.WeekDay)_json["weekDay"].AsInt; }
        { if(!_json["hour"].IsNumber) { throw new SerializationException(); }  Hour = _json["hour"]; }
        { if(!_json["peopleNum"].IsNumber) { throw new SerializationException(); }  PeopleNum = _json["peopleNum"]; }
        { if(!_json["interval"].IsNumber) { throw new SerializationException(); }  Interval = _json["interval"]; }
        PostInit();
    }

    public Crowd(int id, common.WeekDay weekDay, int hour, int peopleNum, int interval ) 
    {
        this.Id = id;
        this.WeekDay = weekDay;
        this.Hour = hour;
        this.PeopleNum = peopleNum;
        this.Interval = interval;
        PostInit();
    }

    public static Crowd DeserializeCrowd(JSONNode _json)
    {
        return new character.Crowd(_json);
    }

    public int Id { get; private set; }
    public common.WeekDay WeekDay { get; private set; }
    public int Hour { get; private set; }
    /// <summary>
    /// 人群人数
    /// </summary>
    public int PeopleNum { get; private set; }
    /// <summary>
    /// 间隔(秒)
    /// </summary>
    public int Interval { get; private set; }

    public const int __ID__ = 1032293768;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "WeekDay:" + WeekDay + ","
        + "Hour:" + Hour + ","
        + "PeopleNum:" + PeopleNum + ","
        + "Interval:" + Interval + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
