//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.character
{ 

public sealed partial class TbSchedule
{
    private readonly Dictionary<int, character.CharacterSchedule> _dataMap;
    private readonly List<character.CharacterSchedule> _dataList;
    
    public TbSchedule(JSONNode _json)
    {
        _dataMap = new Dictionary<int, character.CharacterSchedule>();
        _dataList = new List<character.CharacterSchedule>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = character.CharacterSchedule.DeserializeCharacterSchedule(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, character.CharacterSchedule> DataMap => _dataMap;
    public List<character.CharacterSchedule> DataList => _dataList;

    public character.CharacterSchedule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public character.CharacterSchedule Get(int key) => _dataMap[key];
    public character.CharacterSchedule this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}