//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public character.TbBaseInfo TbBaseInfo {get; }
    public character.TbSchedule TbSchedule {get; }
    public character.TbCharacterBubble TbCharacterBubble {get; }
    public food.TbMaterial TbMaterial {get; }
    public food.TbMenuInfo TbMenuInfo {get; }
    public TbItem TbItem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbBaseInfo = new character.TbBaseInfo(loader("character_tbbaseinfo")); 
        tables.Add("character.TbBaseInfo", TbBaseInfo);
        TbSchedule = new character.TbSchedule(loader("character_tbschedule")); 
        tables.Add("character.TbSchedule", TbSchedule);
        TbCharacterBubble = new character.TbCharacterBubble(loader("character_tbcharacterbubble")); 
        tables.Add("character.TbCharacterBubble", TbCharacterBubble);
        TbMaterial = new food.TbMaterial(loader("food_tbmaterial")); 
        tables.Add("food.TbMaterial", TbMaterial);
        TbMenuInfo = new food.TbMenuInfo(loader("food_tbmenuinfo")); 
        tables.Add("food.TbMenuInfo", TbMenuInfo);
        TbItem = new TbItem(loader("tbitem")); 
        tables.Add("TbItem", TbItem);
        PostInit();

        TbBaseInfo.Resolve(tables); 
        TbSchedule.Resolve(tables); 
        TbCharacterBubble.Resolve(tables); 
        TbMaterial.Resolve(tables); 
        TbMenuInfo.Resolve(tables); 
        TbItem.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbBaseInfo.TranslateText(translator); 
        TbSchedule.TranslateText(translator); 
        TbCharacterBubble.TranslateText(translator); 
        TbMaterial.TranslateText(translator); 
        TbMenuInfo.TranslateText(translator); 
        TbItem.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}