//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public character.TbBaseInfo TbBaseInfo {get; }
    public character.TbSchedule TbSchedule {get; }
    public character.TbCharacterBubble TbCharacterBubble {get; }
    public character.TbCword TbCword {get; }
    public food.TbMaterial TbMaterial {get; }
    public food.TbMenuInfo TbMenuInfo {get; }
    public TbItem TbItem {get; }
    public TbQTE TbQTE {get; }
    public food.TbCookPrefab TbCookPrefab {get; }
    public food.TbFlavour TbFlavour {get; }
    public food.TbQTEGroup TbQTEGroup {get; }
    public system.TbWeatherGroup TbWeatherGroup {get; }
    public system.TbDayScheduler TbDayScheduler {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbBaseInfo = new character.TbBaseInfo(loader("character_tbbaseinfo")); 
        tables.Add("character.TbBaseInfo", TbBaseInfo);
        TbSchedule = new character.TbSchedule(loader("character_tbschedule")); 
        tables.Add("character.TbSchedule", TbSchedule);
        TbCharacterBubble = new character.TbCharacterBubble(loader("character_tbcharacterbubble")); 
        tables.Add("character.TbCharacterBubble", TbCharacterBubble);
        TbCword = new character.TbCword(loader("character_tbcword")); 
        tables.Add("character.TbCword", TbCword);
        TbMaterial = new food.TbMaterial(loader("food_tbmaterial")); 
        tables.Add("food.TbMaterial", TbMaterial);
        TbMenuInfo = new food.TbMenuInfo(loader("food_tbmenuinfo")); 
        tables.Add("food.TbMenuInfo", TbMenuInfo);
        TbItem = new TbItem(loader("tbitem")); 
        tables.Add("TbItem", TbItem);
        TbQTE = new TbQTE(loader("tbqte")); 
        tables.Add("TbQTE", TbQTE);
        TbCookPrefab = new food.TbCookPrefab(loader("food_tbcookprefab")); 
        tables.Add("food.TbCookPrefab", TbCookPrefab);
        TbFlavour = new food.TbFlavour(loader("food_tbflavour")); 
        tables.Add("food.TbFlavour", TbFlavour);
        TbQTEGroup = new food.TbQTEGroup(loader("food_tbqtegroup")); 
        tables.Add("food.TbQTEGroup", TbQTEGroup);
        TbWeatherGroup = new system.TbWeatherGroup(loader("system_tbweathergroup")); 
        tables.Add("system.TbWeatherGroup", TbWeatherGroup);
        TbDayScheduler = new system.TbDayScheduler(loader("system_tbdayscheduler")); 
        tables.Add("system.TbDayScheduler", TbDayScheduler);
        PostInit();

        TbBaseInfo.Resolve(tables); 
        TbSchedule.Resolve(tables); 
        TbCharacterBubble.Resolve(tables); 
        TbCword.Resolve(tables); 
        TbMaterial.Resolve(tables); 
        TbMenuInfo.Resolve(tables); 
        TbItem.Resolve(tables); 
        TbQTE.Resolve(tables); 
        TbCookPrefab.Resolve(tables); 
        TbFlavour.Resolve(tables); 
        TbQTEGroup.Resolve(tables); 
        TbWeatherGroup.Resolve(tables); 
        TbDayScheduler.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbBaseInfo.TranslateText(translator); 
        TbSchedule.TranslateText(translator); 
        TbCharacterBubble.TranslateText(translator); 
        TbCword.TranslateText(translator); 
        TbMaterial.TranslateText(translator); 
        TbMenuInfo.TranslateText(translator); 
        TbItem.TranslateText(translator); 
        TbQTE.TranslateText(translator); 
        TbCookPrefab.TranslateText(translator); 
        TbFlavour.TranslateText(translator); 
        TbQTEGroup.TranslateText(translator); 
        TbWeatherGroup.TranslateText(translator); 
        TbDayScheduler.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}