//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.phone
{ 

public sealed partial class app_news
{
    private readonly Dictionary<int, phone.AppNewsInfo> _dataMap;
    private readonly List<phone.AppNewsInfo> _dataList;
    
    public app_news(JSONNode _json)
    {
        _dataMap = new Dictionary<int, phone.AppNewsInfo>();
        _dataList = new List<phone.AppNewsInfo>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = phone.AppNewsInfo.DeserializeAppNewsInfo(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, phone.AppNewsInfo> DataMap => _dataMap;
    public List<phone.AppNewsInfo> DataList => _dataList;

    public phone.AppNewsInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public phone.AppNewsInfo Get(int key) => _dataMap[key];
    public phone.AppNewsInfo this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}