//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.phone
{ 

public sealed partial class AppBaseInfo :  Bright.Config.BeanBase 
{
    public AppBaseInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["app_icon_res"].IsString) { throw new SerializationException(); }  AppIconRes = _json["app_icon_res"]; }
        { if(!_json["unlock"].IsNumber) { throw new SerializationException(); }  Unlock = _json["unlock"]; }
        PostInit();
    }

    public AppBaseInfo(int id, string name, string app_icon_res, int unlock ) 
    {
        this.Id = id;
        this.Name = name;
        this.AppIconRes = app_icon_res;
        this.Unlock = unlock;
        PostInit();
    }

    public static AppBaseInfo DeserializeAppBaseInfo(JSONNode _json)
    {
        return new phone.AppBaseInfo(_json);
    }

    /// <summary>
    /// appId
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// icon路径
    /// </summary>
    public string AppIconRes { get; private set; }
    /// <summary>
    /// 解锁条件
    /// </summary>
    public int Unlock { get; private set; }

    public const int __ID__ = -1778572352;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "AppIconRes:" + AppIconRes + ","
        + "Unlock:" + Unlock + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
