//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.phone
{ 

public sealed partial class AppNewsInfo :  Bright.Config.BeanBase 
{
    public AppNewsInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["title"].IsString) { throw new SerializationException(); }  Title = _json["title"]; }
        { if(!_json["from"].IsString) { throw new SerializationException(); }  From = _json["from"]; }
        { if(!_json["date"].IsString) { throw new SerializationException(); }  Date = _json["date"]; }
        { if(!_json["preview"].IsString) { throw new SerializationException(); }  Preview = _json["preview"]; }
        { if(!_json["content"].IsString) { throw new SerializationException(); }  Content = _json["content"]; }
        { var __json0 = _json["comments"]; if(!__json0.IsArray) { throw new SerializationException(); } Comments = new System.Collections.Generic.List<phone.news_comment>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { phone.news_comment __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = phone.news_comment.Deserializenews_comment(__e0);  }  Comments.Add(__v0); }   }
        PostInit();
    }

    public AppNewsInfo(int id, string title, string from, string date, string preview, string content, System.Collections.Generic.List<phone.news_comment> comments ) 
    {
        this.Id = id;
        this.Title = title;
        this.From = from;
        this.Date = date;
        this.Preview = preview;
        this.Content = content;
        this.Comments = comments;
        PostInit();
    }

    public static AppNewsInfo DeserializeAppNewsInfo(JSONNode _json)
    {
        return new phone.AppNewsInfo(_json);
    }

    /// <summary>
    /// newsId
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 标题
    /// </summary>
    public string Title { get; private set; }
    /// <summary>
    /// 消息来源
    /// </summary>
    public string From { get; private set; }
    /// <summary>
    /// 时间
    /// </summary>
    public string Date { get; private set; }
    /// <summary>
    /// 预览图
    /// </summary>
    public string Preview { get; private set; }
    /// <summary>
    /// 正文内容
    /// </summary>
    public string Content { get; private set; }
    /// <summary>
    /// nick_name
    /// </summary>
    public System.Collections.Generic.List<phone.news_comment> Comments { get; private set; }

    public const int __ID__ = 1337775810;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Comments) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Comments) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Title:" + Title + ","
        + "From:" + From + ","
        + "Date:" + Date + ","
        + "Preview:" + Preview + ","
        + "Content:" + Content + ","
        + "Comments:" + Bright.Common.StringUtil.CollectionToString(Comments) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
