//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.phone
{ 

public sealed partial class news_comment :  Bright.Config.BeanBase 
{
    public news_comment(JSONNode _json) 
    {
        { if(!_json["nick_name"].IsString) { throw new SerializationException(); }  NickName = _json["nick_name"]; }
        { if(!_json["comment"].IsString) { throw new SerializationException(); }  Comment = _json["comment"]; }
        { if(!_json["like"].IsNumber) { throw new SerializationException(); }  Like = _json["like"]; }
        { if(!_json["unlike"].IsNumber) { throw new SerializationException(); }  Unlike = _json["unlike"]; }
        PostInit();
    }

    public news_comment(string nick_name, string comment, int like, int unlike ) 
    {
        this.NickName = nick_name;
        this.Comment = comment;
        this.Like = like;
        this.Unlike = unlike;
        PostInit();
    }

    public static news_comment Deserializenews_comment(JSONNode _json)
    {
        return new phone.news_comment(_json);
    }

    /// <summary>
    /// 昵称
    /// </summary>
    public string NickName { get; private set; }
    /// <summary>
    /// 评论
    /// </summary>
    public string Comment { get; private set; }
    /// <summary>
    /// 点赞
    /// </summary>
    public int Like { get; private set; }
    /// <summary>
    /// 点踩
    /// </summary>
    public int Unlike { get; private set; }

    public const int __ID__ = 571362675;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "NickName:" + NickName + ","
        + "Comment:" + Comment + ","
        + "Like:" + Like + ","
        + "Unlike:" + Unlike + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
