//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.phone
{ 

public sealed partial class TbAppBaseInfo
{
    private readonly Dictionary<int, phone.AppBaseInfo> _dataMap;
    private readonly List<phone.AppBaseInfo> _dataList;
    
    public TbAppBaseInfo(JSONNode _json)
    {
        _dataMap = new Dictionary<int, phone.AppBaseInfo>();
        _dataList = new List<phone.AppBaseInfo>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = phone.AppBaseInfo.DeserializeAppBaseInfo(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, phone.AppBaseInfo> DataMap => _dataMap;
    public List<phone.AppBaseInfo> DataList => _dataList;

    public phone.AppBaseInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public phone.AppBaseInfo Get(int key) => _dataMap[key];
    public phone.AppBaseInfo this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}