//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.item
{ 
    public enum itemType
    {
        /// <summary>
        /// 食材
        /// </summary>
        FoodMaterial = 1,
        /// <summary>
        /// 菜谱
        /// </summary>
        Receipt = 2,
        /// <summary>
        /// 货币
        /// </summary>
        Currency = 3,
    }

} 
